{% set python_min = "3.11" %}
{%- set name = "diffpy.morph" -%}
{%- set version = "0.2.0" -%}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_morph/diffpy_morph-{{ version }}.tar.gz
  sha256: fe3741623877907f2d5b002b36c0bb3086493008f9e97a40509023165ab9af38

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - diffpy.morph = diffpy.morph.morphapp:main

requirements:
  build:

  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - diffpy.utils >=3.6.1
    - matplotlib-base
    - bg-mpl-stylesheets

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest

  source_files:
    - tests

  commands:
    - pip check
    - pytest

about:
  home: https://github.com/diffpy/diffpy.morph/
  summary: Python package for manipulating and comparing 1D signals.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    diffpy.morph is a Python software package designed to increase the insight researchers can obtain from comparing 1D signals/functions in a model-independent way.
    The program finds the best 'morphs' (e.g. x/y-axis scaling, shifting, Gaussian smearing) to apply to transform one signal to another target signal.
    The program was originally designed to help researchers determine whether a phase transition has occurred across two spectral data measured at different temperatures.
  doc_url: http://diffpy.github.io/diffpy.morph/
  dev_url: https://github.com/diffpy/diffpy.morph/

extra:
  recipe-maintainers:
    - Sparks29032
    - Luiskitsu
    - bobleesj
    - sbillinge
